apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mysqldb
spec:
  schedule: {{ .Values.backup.cron_for_full_backup |  quote }}
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            {{- toYaml .Values.affinity | nindent 12 }}
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred
          serviceAccountName: sa-mysql-backup
          containers:
          - name: backup-mysqldb
            image: squareops/mysqldb-backup:v5
            imagePullPolicy: Always
            env:
            - name: MYSQL_HOST
              value: mysqldb-secondary-headless.{{ .Release.Namespace }}.svc.cluster.local
            - name: MYSQL_USER
              value: {{ .Values.auth.username }}
            - name: DATABASES
              value: {{ .Values.backup.database_name }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mysqldb
                    key: mysql-root-password
            - name: MYSQL_BUCKET_URI
              valueFrom:
                secretKeyRef:
                  name: mysql-bucket-uri
                  key: MYSQL_BUCKET_URI
            - name: BUCKET_PROVIDER
              value:  "s3"
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.backup.aws_default_region }}
            resources:
              {{- toYaml .Values.backupjob.resources | nindent 14 }}
