restore:
  bucket_uri: ${bucket_uri}
  file_name: ${file_name}
  aws_default_region: ${s3_bucket_region}

auth:
  username: "${custom_user_username}"

annotations:
  ${annotations}

bucket_provider_type: ${bucket_provider_type}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Infra-Services"
          operator: In
          values:
          - "true"

restorejob:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
